services:
    php-cli:
        build: docker/php-cli
        container_name: '${DOCKER_CONTAINER_BASE_NAME}-php-cli'
        volumes:
            - './:/var/www/'
        working_dir: /var/www
        profiles:
            - on-demand
        networks:
            - app_network
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        container_name: '${DOCKER_CONTAINER_BASE_NAME}-app'
        ports:
            - '8081:8080'
        networks:
            - app_network
networks:
    app_network:
        name: '${DOCKER_CONTAINER_BASE_NAME}_app'
volumes:
    database_data: null
