services:
    php-cli:
        build: docker/php-cli
        container_name: 'strava-statistics-php-cli'
        volumes:
            - './:/var/www/'
        working_dir: /var/www
        environment:
            - PHP_CS_FIXER_IGNORE_ENV=true
            - IMPORT_AND_BUILD_SCHEDULE=* * * * *
            - PHP_IDE_CONFIG=phpstorm
        profiles:
            - on-demand
        networks:
            - strava-statistics-network
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        container_name: 'strava-statistics-app'
        volumes:
            - ./build:/var/www/build
            - ./storage/database:/var/www/storage/database
            - ./storage/files:/var/www/storage/files
            #- ./cron:/config/crontabs
        env_file: ".env.local"
        ports:
            - '8081:8080'
        networks:
            - strava-statistics-network

    ollama:
        image: ollama/ollama:latest
        container_name: 'strava-statistics-ollama'
        tty: true
        restart: unless-stopped
        volumes:
            - .:/code
            - ./ollama:/root/.ollama
        environment:
            - OLLAMA_KEEP_ALIVE=24h
            - OLLAMA_HOST=0.0.0.0
        ports:
            - '11434:11434'
        networks:
            - strava-statistics-network
networks:
    strava-statistics-network: {}
