services:
    php-cli:
        build: docker/php-cli
        container_name: 'strava-statistics-php-cli'
        volumes:
            - './:/var/www/'
        working_dir: /var/www
        profiles:
            - on-demand
        networks:
            - app_network
    app:
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        container_name: 'strava-statistics-app'
        volumes:
            - ./database:/var/www/database
        ports:
            - '8081:8080'
        networks:
            - app_network
networks:
    app_network: {}
